### ISSUE TITLE
"Pomodoro history" click is ignored

### ISSUE THREAD

**Issue by sohich** [schmich/marinara#212]
**OS:** Windows 8.1 64-bit
**Browser:** Chrome v. 69.0.3497.10 64-bit

Even if no plugin tabs opened in browser, nothing happens when i click the history option in the plugin options menu.

**Comment by sohich** [comment]
```
Error in response to tabs.update: TypeError: Cannot read property 'windowId' of undefined
    at Object.focusWindow [as callback] (chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/background/notifications.js:102:58)
    at focusTab (chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/background/notifications.js:105:21)
    at SingletonPage.focus (chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/background/notifications.js:112:5)
    at Function.show (chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/background/notifications.js:77:12)
    at Controller.showOptionsPage (chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/background/background.js:125:25)
    at PomodoroHistoryAction.run (chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/background/menu.js:257:21)
    at onclick (chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/background/menu.js:52:33)


Unchecked runtime.lastError while running tabs.update: No tab with id: 1650462523.
    at focusTab (chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/background/notifications.js:105:21)
    at SingletonPage.focus (chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/background/notifications.js:112:5)
    at Function.show (chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/background/notifications.js:77:12)
    at Controller.showOptionsPage (chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/background/background.js:125:25)
    at PomodoroHistoryAction.run (chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/background/menu.js:257:21)
    at onclick (chrome-extension://lojgmehidjdhhbmpjfamhpkpodfcodef/background/menu.js:52:33)
```
